/*
 * IRS API
 *
 * Package github.com/moov-io/irs implements a file reader and writer written in Go along with a HTTP API and CLI for creating, parsing, validating, and transforming IRS electronic Filing Information Returns Electronically (FIRE). FIRE operates on a byte(ASCII) level making it difficult to interface with JSON and CSV/TEXT file formats. | Input      | Output     | |------------|------------| | JSON       | JSON       | | ASCII FIRE | ASCII FIRE | |            | PDF Form   | |            | SQL        |
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ARecord struct for ARecord
type ARecord struct {
	RecordType                 string `json:"record_type"`
	PaymentYear                int32  `json:"payment_year"`
	CombinedFsFilingProgram    string `json:"combined_fs_filing_program,omitempty"`
	PayerTin                   string `json:"payer_tin"`
	PayerNameControl           string `json:"payer_name_control,omitempty"`
	LastFilingIndicator        string `json:"last_filing_indicator,omitempty"`
	TypeOfReturn               string `json:"type_of_return"`
	AmountCodes                string `json:"amount_codes"`
	ForeignEntityIndicator     string `json:"foreign_entity_indicator,omitempty"`
	FirstPayerName             string `json:"first_payer_name"`
	SecondPayerName            string `json:"second_payer_name,omitempty"`
	TransferAgentControl       string `json:"transfer_agent_control"`
	PayerShippingAddress       string `json:"payer_shipping_address"`
	PayerCity                  string `json:"payer_city"`
	PayerState                 string `json:"payer_state"`
	PayerZipCode               string `json:"payer_zip_code"`
	PayerTelephoneNumberAndExt string `json:"payer_telephone_number_and_ext,omitempty"`
	RecordSequenceNumber       int32  `json:"record_sequence_number"`
}
