/*
 * IRS API
 *
 * Package github.com/moov-io/irs implements a file reader and writer written in Go along with a HTTP API and CLI for creating, parsing, validating, and transforming IRS electronic Filing Information Returns Electronically (FIRE). FIRE operates on a byte(ASCII) level making it difficult to interface with JSON and CSV/TEXT file formats. | Input      | Output     | |------------|------------| | JSON       | JSON       | | ASCII FIRE | ASCII FIRE | |            | PDF Form   | |            | SQL        | 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// TRecord struct for TRecord
type TRecord struct {
	RecordType string `json:"record_type"`
	PaymentYear int32 `json:"payment_year"`
	PriorYearDataIndicator string `json:"prior_year_data_indicator"`
	TransmitterTin string `json:"transmitter_tin"`
	TransmitterControlCode string `json:"transmitter_control_code"`
	TestFileIndicator string `json:"test_file_indicator,omitempty"`
	ForeignEntityIndicator string `json:"foreign_entity_indicator,omitempty"`
	TransmitterName string `json:"transmitter_name"`
	TransmitterNameContd string `json:"transmitter_name_contd,omitempty"`
	CompanyName string `json:"company_name"`
	CompanyNameContd string `json:"company_name_contd,omitempty"`
	CompanyMailingAddress string `json:"company_mailing_address"`
	CompanyCity string `json:"company_city"`
	CompanyState string `json:"company_state"`
	CompanyZipCode string `json:"company_zip_code"`
	TotalNumberOfPayees int32 `json:"total_number_of_payees,omitempty"`
	ContactName string `json:"contact_name"`
	ContactTelephoneNumberAndExt string `json:"contact_telephone_number_and_ext"`
	ContactEmailAddress string `json:"contact_email_address,omitempty"`
	RecordSequenceNumber int32 `json:"record_sequence_number"`
	VendorIndicator string `json:"vendor_indicator"`
	VendorName string `json:"vendor_name"`
	VendorMailingAddress string `json:"vendor_mailing_address"`
	VendorCity string `json:"vendor_city"`
	VendorState string `json:"vendor_state"`
	VendorZipCode string `json:"vendor_zip_code"`
	VendorContactName string `json:"vendor_contact_name"`
	VendorContactTelephoneAndExt string `json:"vendor_contact_telephone_and_ext"`
	VendorForeignEntityIndicator string `json:"vendor_foreign_entity_indicator"`
}
