/*
 * IRS API
 *
 * Package github.com/moov-io/irs implements a file reader and writer written in Go along with a HTTP API and CLI for creating, parsing, validating, and transforming IRS electronic Filing Information Returns Electronically (FIRE). FIRE operates on a byte(ASCII) level making it difficult to interface with JSON and CSV/TEXT file formats.  | Input      | Output     |  |------------|------------|  | JSON       | JSON       |  | ASCII FIRE | ASCII FIRE |  |            | PDF Form   |  |            | SQL        |
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// FRecord struct for FRecord
type FRecord struct {
	RecordType           string `json:"record_type"`
	NumberOfPayerRecords int32  `json:"number_of_payer_records,omitempty"`
	TotalNumberOfPayees  int32  `json:"total_number_of_payees,omitempty"`
	RecordSequenceNumber int32  `json:"record_sequence_number"`
}
